setup

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/application_train.csv")

print(df.shape)

(307511, 122)

In [2]:
df["DAYS_EMPLOYED"] = df["DAYS_EMPLOYED"].replace(
    365243,
    np.nan
)

In [3]:
df["AGE_YEARS"] = (
    -df["DAYS_BIRTH"] / 365.25
)

df["EMPLOYMENT_YEARS"] = (
    -df["DAYS_EMPLOYED"] / 365.25
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\1966075138.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["AGE_YEARS"] = (
C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\1966075138.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["EMPLOYMENT_YEARS"] = (

In [4]:
df[[
    "AGE_YEARS",
    "EMPLOYMENT_YEARS"
]].describe()

           AGE_YEARS  EMPLOYMENT_YEARS
count  307511.000000     252137.000000
mean       43.906900          6.527500
std        11.947950          6.402081
min        20.503765         -0.000000
25%        33.984942          2.099932
50%        43.121150          4.511978
75%        53.886379          8.692676
max        69.073238         49.040383

In [5]:
df["INCOME_TO_CREDIT_RATIO"] = (
    df["AMT_INCOME_TOTAL"] /
    df["AMT_CREDIT"]
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\788355638.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["INCOME_TO_CREDIT_RATIO"] = (

In [6]:
df["CREDIT_TO_INCOME_RATIO"] = (
    df["AMT_CREDIT"] /
    df["AMT_INCOME_TOTAL"]
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\3988192865.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["CREDIT_TO_INCOME_RATIO"] = (

In [7]:
df["ANNUITY_TO_INCOME_RATIO"] = (
    df["AMT_ANNUITY"] /
    df["AMT_INCOME_TOTAL"]
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\2829621699.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["ANNUITY_TO_INCOME_RATIO"] = (

In [8]:
df["CREDIT_TO_ANNUITY_RATIO"] = (
    df["AMT_CREDIT"] /
    df["AMT_ANNUITY"]
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\1623724815.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["CREDIT_TO_ANNUITY_RATIO"] = (

In [9]:
df["CREDIT_TO_ANNUITY_RATIO"].describe()

count    307499.000000
mean         21.612322
std           7.823823
min           8.036674
25%          15.614496
50%          20.000000
75%          27.099985
max          45.305079
Name: CREDIT_TO_ANNUITY_RATIO, dtype: float64

In [10]:
df["CREDIT_TO_GOODS_RATIO"] = (
    df["AMT_CREDIT"] /
    df["AMT_GOODS_PRICE"]
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\3684352003.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["CREDIT_TO_GOODS_RATIO"] = (

In [11]:
df["INCOME_PER_PERSON"] = (
    df["AMT_INCOME_TOTAL"] /
    df["CNT_FAM_MEMBERS"]
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\3765874970.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["INCOME_PER_PERSON"] = (

In [12]:
df["CHILDREN_RATIO"] = (
    df["CNT_CHILDREN"] /
    df["CNT_FAM_MEMBERS"]
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\4126250587.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["CHILDREN_RATIO"] = (

In [13]:
df["EMPLOYMENT_TO_AGE_RATIO"] = (
    df["EMPLOYMENT_YEARS"] /
    df["AGE_YEARS"]
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\23732769.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["EMPLOYMENT_TO_AGE_RATIO"] = (

In [14]:
df["AGE_GROUP"] = pd.cut(
    df["AGE_YEARS"],
    bins=[0, 25, 35, 45, 55, 65, 100],
    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56-65",
        "65+"
    ]
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\1965044106.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["AGE_GROUP"] = pd.cut(

In [15]:
df["AGE_GROUP"].value_counts(dropna=False)

AGE_GROUP
36-45    84261
26-35    72429
46-55    70190
56-65    60522
18-25    12233
65+       7876
Name: count, dtype: int64

In [16]:
df["EMPLOYMENT_GROUP"] = pd.cut(
    df["EMPLOYMENT_YEARS"],
    bins=[-1, 1, 3, 5, 10, 20, 100],
    labels=[
        "<1 Year",
        "1-3 Years",
        "3-5 Years",
        "5-10 Years",
        "10-20 Years",
        "20+ Years"
    ]
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\1981729544.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["EMPLOYMENT_GROUP"] = pd.cut(

In [17]:
document_columns = [
    column
    for column in df.columns
    if column.startswith("FLAG_DOCUMENT")
]

print("Number of document columns:", len(document_columns))

Number of document columns: 20

In [18]:
df["TOTAL_DOCUMENTS_SUBMITTED"] = (
    df[document_columns].sum(axis=1)
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\570759061.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["TOTAL_DOCUMENTS_SUBMITTED"] = (

In [19]:
external_sources = [
    "EXT_SOURCE_1",
    "EXT_SOURCE_2",
    "EXT_SOURCE_3"
]

In [20]:
df["EXT_SOURCE_MEAN"] = (
    df[external_sources].mean(axis=1)
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\1783518440.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["EXT_SOURCE_MEAN"] = (

In [21]:
df["EXT_SOURCE_MAX"] = (
    df[external_sources].max(axis=1)
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\1401242972.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["EXT_SOURCE_MAX"] = (

In [22]:
df["EXT_SOURCE_MIN"] = (
    df[external_sources].min(axis=1)
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\1904169166.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["EXT_SOURCE_MIN"] = (

In [23]:
df["EXT_SOURCE_STD"] = (
    df[external_sources].std(axis=1)
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\4205084961.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["EXT_SOURCE_STD"] = (

In [24]:
df["EXT_SOURCE_COUNT"] = (
    df[external_sources].notna().sum(axis=1)
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\4087288256.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["EXT_SOURCE_COUNT"] = (

In [25]:
contact_columns = [
    "FLAG_MOBIL",
    "FLAG_EMP_PHONE",
    "FLAG_WORK_PHONE",
    "FLAG_CONT_MOBILE",
    "FLAG_PHONE",
    "FLAG_EMAIL"
]

In [26]:
df["TOTAL_CONTACT_FLAGS"] = (
    df[contact_columns].sum(axis=1)
)

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\2103497898.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["TOTAL_CONTACT_FLAGS"] = (

In [27]:
new_features = [
    "AGE_YEARS",
    "EMPLOYMENT_YEARS",
    "INCOME_TO_CREDIT_RATIO",
    "CREDIT_TO_INCOME_RATIO",
    "ANNUITY_TO_INCOME_RATIO",
    "CREDIT_TO_ANNUITY_RATIO",
    "CREDIT_TO_GOODS_RATIO",
    "INCOME_PER_PERSON",
    "CHILDREN_RATIO",
    "EMPLOYMENT_TO_AGE_RATIO",
    "AGE_GROUP",
    "EMPLOYMENT_GROUP",
    "TOTAL_DOCUMENTS_SUBMITTED",
    "EXT_SOURCE_MEAN",
    "EXT_SOURCE_MAX",
    "EXT_SOURCE_MIN",
    "EXT_SOURCE_STD",
    "EXT_SOURCE_COUNT",
    "TOTAL_CONTACT_FLAGS"
]

In [28]:
df[new_features].head()

,AGE_YEARS,EMPLOYMENT_YEARS,INCOME_TO_CREDIT_RATIO,CREDIT_TO_INCOME_RATIO,ANNUITY_TO_INCOME_RATIO,CREDIT_TO_ANNUITY_RATIO,CREDIT_TO_GOODS_RATIO,INCOME_PER_PERSON,CHILDREN_RATIO,EMPLOYMENT_TO_AGE_RATIO,AGE_GROUP,EMPLOYMENT_GROUP,TOTAL_DOCUMENTS_SUBMITTED,EXT_SOURCE_MEAN,EXT_SOURCE_MAX,EXT_SOURCE_MIN,EXT_SOURCE_STD,EXT_SOURCE_COUNT,TOTAL_CONTACT_FLAGS
0,25.902806,1.744011,0.498036,2.007889,0.121978,16.461104,1.158397,202500.0,0.0,0.067329,26-35,1-3 Years,1,0.161787,0.262949,0.083037,0.092026,3,4
1,45.900068,3.252567,0.208736,4.790750,0.132217,36.234085,1.145199,135000.0,0.0,0.070862,46-55,3-5 Years,1,0.466757,0.622246,0.311267,0.219895,2,4
2,52.145106,0.616016,0.500000,2.000000,0.100000,20.000000,1.000000,67500.0,0.0,0.011814,46-55,<1 Year,0,0.642739,0.729567,0.555912,0.122792,2,5
3,52.032854,8.320329,0.431748,2.316167,0.219900,10.532818,1.052803,67500.0,0.0,0.159905,46-55,5-10 Years,1,0.650442,0.650442,0.650442,NaN,1,3
4,54.570842,8.317591,0.236842,4.222222,0.179963,23.461618,1.000000,121500.0,0.0,0.152418,46-55,5-10 Years,1,0.322738,0.322738,0.322738,NaN,1,3

In [29]:
df.select_dtypes(
    include=["int64", "float64"]
)[new_features[:10]].describe()

,AGE_YEARS,EMPLOYMENT_YEARS,INCOME_TO_CREDIT_RATIO,CREDIT_TO_INCOME_RATIO,ANNUITY_TO_INCOME_RATIO,CREDIT_TO_ANNUITY_RATIO,CREDIT_TO_GOODS_RATIO,INCOME_PER_PERSON,CHILDREN_RATIO,EMPLOYMENT_TO_AGE_RATIO
count,307511.000000,252137.000000,307511.000000,307511.000000,307499.000000,307499.000000,307233.000000,3.075090e+05,307509.000000,252137.000000
mean,43.906900,6.527500,0.399670,3.957570,0.180930,21.612322,1.122995,9.310588e+04,0.125502,0.156861
std,11.947950,6.402081,0.507924,2.689728,0.094574,7.823823,0.124045,1.013734e+05,0.199578,0.133549
min,20.503765,-0.000000,0.011801,0.004808,0.000224,8.036674,0.150000,2.812500e+03,0.000000,-0.000000
25%,33.984942,2.099932,0.193803,2.018667,0.114782,15.614496,1.000000,4.725000e+04,0.000000,0.056099
50%,43.121150,4.511978,0.306272,3.265067,0.162833,20.000000,1.118800,7.500000e+04,0.000000,0.118733
75%,53.886379,8.692676,0.495376,5.159880,0.229067,27.099985,1.198000,1.125000e+05,0.333333,0.219170
max,69.073238,49.040383,208.003328,84.736842,1.875965,45.305079,6.000000,3.900000e+07,0.950000,0.728811

In [30]:
numeric_df = df.select_dtypes(
    include=[np.number]
)

infinite_values = np.isinf(
    numeric_df.to_numpy()
).sum()

print("Infinite values:", infinite_values)

Infinite values: 0

In [31]:
df.replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,EMPLOYMENT_TO_AGE_RATIO,AGE_GROUP,EMPLOYMENT_GROUP,TOTAL_DOCUMENTS_SUBMITTED,EXT_SOURCE_MEAN,EXT_SOURCE_MAX,EXT_SOURCE_MIN,EXT_SOURCE_STD,EXT_SOURCE_COUNT,TOTAL_CONTACT_FLAGS
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0.067329,26-35,1-3 Years,1,0.161787,0.262949,0.083037,0.092026,3,4
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0.070862,46-55,3-5 Years,1,0.466757,0.622246,0.311267,0.219895,2,4
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0.011814,46-55,<1 Year,0,0.642739,0.729567,0.555912,0.122792,2,5
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0.159905,46-55,5-10 Years,1,0.650442,0.650442,0.650442,NaN,1,3
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0.152418,46-55,5-10 Years,1,0.322738,0.322738,0.322738,NaN,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,Cash loans,M,N,N,0,157500.0,254700.0,27558.0,...,0.025303,26-35,<1 Year,1,0.413601,0.681632,0.145570,0.379053,2,3
307507,456252,0,Cash loans,F,N,Y,0,72000.0,269550.0,12001.5,...,NaN,56-65,NaN,1,0.115992,0.115992,0.115992,NaN,1,3
307508,456253,0,Cash loans,F,N,Y,0,153000.0,677664.0,29979.0,...,0.529266,36-45,20+ Years,1,0.499536,0.744026,0.218859,0.264447,3,4
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0.400134,26-35,10-20 Years,1,0.587593,0.661024,0.514163,0.103846,2,3
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0.074869,46-55,3-5 Years,1,0.518984,0.734460,0.113922,0.351032,3,5

In [32]:
X = df.drop(
    columns=[
        "TARGET",
        "SK_ID_CURR"
    ]
)

y = df["TARGET"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (307511, 139)
y shape: (307511,)

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [35]:
numerical_features = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("Numerical:", len(numerical_features))
print("Categorical:", len(categorical_features))

Numerical: 121
Categorical: 18

C:\Users\Charan\AppData\Local\Temp\ipykernel_10400\302416908.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes(

In [36]:
numerical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)

In [37]:
categorical_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)

In [38]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numerical_transformer,
            numerical_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        )
    ]
)

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

logistic_engineered = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            LogisticRegression(
                max_iter=1000,
                class_weight="balanced",
                random_state=42
            )
        )
    ]
)

logistic_engineered.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['CNT_CHILDREN',
                                                   'AMT_INCOME_TOTAL',
                                                   'AMT_CREDIT', 'AMT_ANNUITY',
                                                   'AMT_GOODS_PRICE',
                                                   'REGION_POPULATION_RELATIVE',
                                                   'DAYS_BIRTH',
                                                   'DAYS_EMPLOYED',
                                                   'DAYS_REGISTRATION',
                                                   'DAYS_ID_PUBLISH',
                                                   'OWN_CAR_AGE...
                                                   'NAME_INCOME_TYPE',
                                                   'NAME_EDUCATION_TYPE',
                                                   'NAME_FAMILY_STATUS',
                                                   'NAME_HOUSING_TYPE',
                                                   'OCCUPATION_TYPE',
                                                   'WEEKDAY_APPR_PROCESS_START',
                                                   'ORGANIZATION_TYPE',
                                                   'FONDKAPREMONT_MODE',
                                                   'HOUSETYPE_MODE',
                                                   'WALLSMATERIAL_MODE',
                                                   'EMERGENCYSTATE_MODE',
                                                   'AGE_GROUP',
                                                   'EMPLOYMENT_GROUP'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

logistic_engineered = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            LogisticRegression(
                max_iter=1000,
                class_weight="balanced",
                random_state=42
            )
        )
    ]
)

logistic_engineered.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['CNT_CHILDREN',
                                                   'AMT_INCOME_TOTAL',
                                                   'AMT_CREDIT', 'AMT_ANNUITY',
                                                   'AMT_GOODS_PRICE',
                                                   'REGION_POPULATION_RELATIVE',
                                                   'DAYS_BIRTH',
                                                   'DAYS_EMPLOYED',
                                                   'DAYS_REGISTRATION',
                                                   'DAYS_ID_PUBLISH',
                                                   'OWN_CAR_AGE...
                                                   'NAME_INCOME_TYPE',
                                                   'NAME_EDUCATION_TYPE',
                                                   'NAME_FAMILY_STATUS',
                                                   'NAME_HOUSING_TYPE',
                                                   'OCCUPATION_TYPE',
                                                   'WEEKDAY_APPR_PROCESS_START',
                                                   'ORGANIZATION_TYPE',
                                                   'FONDKAPREMONT_MODE',
                                                   'HOUSETYPE_MODE',
                                                   'WALLSMATERIAL_MODE',
                                                   'EMERGENCYSTATE_MODE',
                                                   'AGE_GROUP',
                                                   'EMPLOYMENT_GROUP'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_engineered = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            RandomForestClassifier(
                n_estimators=200,
                max_depth=15,
                min_samples_split=10,
                min_samples_leaf=5,
                class_weight="balanced",
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)

rf_engineered.fit(
    X_train,
    y_train
)

In [ ]:
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

def evaluate_model(name, model, X_test, y_test):
    
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]
    
    return {
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(
            y_test,
            y_pred,
            zero_division=0
        ),
        "Recall": recall_score(
            y_test,
            y_pred,
            zero_division=0
        ),
        "F1": f1_score(
            y_test,
            y_pred,
            zero_division=0
        ),
        "ROC-AUC": roc_auc_score(
            y_test,
            y_prob
        ),
        "PR-AUC": average_precision_score(
            y_test,
            y_prob
        )
    }

In [ ]:
comparison_df = pd.DataFrame([
    engineered_logistic_results,
    engineered_rf_results
])

comparison_df.round(4)